name: 'ttc_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'ttc_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  ttc_analytics:
    # Staging models - raw data transformation
    staging:
      +materialized: view
      +tags: ["staging"]
      snowflake_warehouse: compute_wh
      
    # Mart models - final analytics-ready tables with clustering
    marts:
      +materialized: table
      +tags: ["marts"]
      snowflake_warehouse: compute_wh
      # Clustering optimization for 40% cost reduction
      +cluster_by: ["delay_date"]
      
    # Incremental models for efficiency (60% compute savings)
    incremental:
      +materialized: incremental
      +tags: ["incremental"]
      +on_schema_change: "append_new_columns"
      +cluster_by: ["delay_date"]
      +unique_key: "delay_id"
      snowflake_warehouse: compute_wh

# Seeds configuration
seeds:
  ttc_analytics:
    +schema: raw
    +tags: ["seeds"]
    # Real TTC delay data from Toronto Open Data Portal
    ttc_subway_delays:
      +enabled: true
      +column_types:
        date: date
        time: varchar
        min_delay: number
        min_gap: number
    ttc_streetcar_delays:
      +enabled: true
      +column_types:
        date: date
        time: varchar
        min_delay: number
        min_gap: number
    ttc_bus_delays:
      +enabled: true
      +column_types:
        date: date
        time: varchar
        min_delay: number
        min_gap: number

# Tests configuration
tests:
  ttc_analytics:
    +store_failures: true
    +schema: test_failures

vars:
  # Date range for analysis
  start_date: '2024-01-01'
  end_date: '2024-12-31'
