# This file should be placed in ~/.dbt/ directory
# Copy this template and update with your Snowflake credentials

ttc_analytics:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ACCOUNTADMIN') }}"
      database: TTC_ANALYTICS
      warehouse: COMPUTE_WH
      schema: dev
      threads: 4
      client_session_keep_alive: False
      query_tag: dbt_ttc_analytics
      
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ACCOUNTADMIN') }}"
      database: TTC_ANALYTICS
      warehouse: COMPUTE_WH
      schema: prod
      threads: 8
      client_session_keep_alive: False
      query_tag: dbt_ttc_analytics

