name: dbt CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  dbt-test:
    name: dbt Build and Test
    runs-on: ubuntu-latest

    env:
      DBT_PROFILES_DIR: .
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dbt packages
        run: dbt deps

      - name: Check dbt version
        run: dbt --version

      - name: Run dbt debug
        run: dbt debug --target dev

      - name: Run dbt compile
        run: dbt compile --target dev

      - name: Run dbt build (models + tests)
        run: dbt build --target dev --full-refresh

      - name: Generate dbt docs
        run: dbt docs generate --target dev

      - name: Upload dbt artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: dbt-artifacts
          path: |
            target/manifest.json
            target/run_results.json
            target/catalog.json
            target/index.html

  sqlfluff-lint:
    name: SQLFluff Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install SQLFluff
        run: |
          pip install sqlfluff sqlfluff-templater-dbt

      - name: Lint SQL files
        run: |
          sqlfluff lint models/ --dialect snowflake || true

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [dbt-test, sqlfluff-lint]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    env:
      DBT_PROFILES_DIR: .
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install dbt packages
        run: dbt deps

      - name: Deploy to Production
        run: dbt build --target prod

      - name: Generate and deploy docs
        run: |
          dbt docs generate --target prod
          echo "Documentation generated successfully"

